FROM apache/airflow:2.10.3

# Herramientas del SO (git y venv)
USER root
RUN apt-get update && apt-get install -y git python3-venv && rm -rf /var/lib/apt/lists/*

# Volver a usuario airflow y crear un venv aislado para tus binarios
USER airflow
RUN python -m venv /opt/airflow/.venvs/tools \
 && /opt/airflow/.venvs/tools/bin/pip install --upgrade pip \
 && /opt/airflow/.venvs/tools/bin/pip install "kedro==0.19.8" "dvc[gdrive]==3.33.2"





